version: '3.6'

services:
  mongodb:
    image: mongo:4
    env_file: .env
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017-27019:27017-27019'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  mongodb_web:
    image: mongo-express
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - '8091:8081'

volumes:
  mongo-data:
